### ISSUE TITLE
Discrepancy in location of PAM [featurization.py]

### ISSUE THREAD

**Issue by Wainberg** [MicrosoftResearch/Azimuth#1]
http://www.nature.com/nbt/journal/v32/n12/fig_tab/nbt.3026_F3.html shows the PAM at positions 24-27 within the 30-mer (using zero-based Python indexing) and the length-20 targeting sequence at positions 4-24.  Azimuth's pam_audit code uses this definition, since it requires a 'GG' at seq[25:27].  nucleotide_features_dictionary also uses this definition.

However, countGC assumes the targeting sequence is at positions 5-25: return len(s[5:25].replace('A', '').replace('T', '')).  Tm_feature also assumes this: featarray[i,1] = Tm.Tm_staluc(seq[20:25], rna=rna) #5nts immediately proximal of the NGG PAM.  These seem incorrect.  Could you clarify in the documentation whether the targeting sequence is at positions 4-24 or 5-25?

Thanks for making this tool available to the community!

**Comment by jlistgarten** [comment]
Thanks for catching this. The targeting sequence is indeed 4-24, and we have now fixed countGC and the thermodynamic features to reflect this. Additionally, we have re-run the final set of features with the final AdaBoosted model and tuning parameters to ensure that this does not change the reported results in any substantial way, and it does not. However, we will soon be checking in an updated model for consistency between the newly fixed code and the saved model.
