### ISSUE TITLE
Running into issues while installing Azimuth on Windows, Need more clear installation docs

### ISSUE THREAD

**Issue by sudheesh001** [MicrosoftResearch/Azimuth#10]
Hey,

I've been trying to install Azimuth on Windows 10 and have been running into problems even after installing http://aka.ms/vcpython27

It'd be nice to have some clear documentation of the setup process and the list of required libraries needed to get this running. Here's the log
https://gist.github.com/sudheesh001/2b70e0ed4371032cab58d1efa367cee3

**Comment by nfusi** [comment]
Have you tried using the Anaconda python distribution? https://www.continuum.io/downloads
You can then run "conda install biopython", which should solve your problem.

We are going to add a note in the readme page pointing users to Anaconda as the preferred python distribution. Thanks!

**Comment by sudheesh001** [comment]
I've done `conda install biopython` and then re ran the `python setup.py install` to set up azimuth but it seems to fail again with the same result. FreeType and PNG look like required dependencies which are failing but that's in building matplotlib.

Any workarounds ?

**Comment by nfusi** [comment]
Have you tried running `conda install matplotlib` before `python setup.py install`? Can you post the full error message?

**Comment by sudheesh001** [comment]
Yup, I've done the following
`conda install biopython`
`conda install matplotlib`
`python setup.py install`

Here's the log: https://gist.github.com/sudheesh001/9cc04fbf7df9813d479221409a04f0fd

It ends with

``` log
OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: no  [PyQt5 not found]
                qt4agg: no  [PySide not found; PyQt4 not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: yes [installing; run-time loading from Python Tcl /
                        Tk]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairocffi or pycairo not found]
             windowing: yes [installing]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

OPTIONAL PACKAGE DATA
                  dlls: no  [skipping due to configuration]

============================================================================
                        * The following required packages can not be built:
                        * freetype, png
error: Setup script exited with 1

C:\Users\susingan\Documents\Microsoft\Azimuth>
```

![biopython](https://cloud.githubusercontent.com/assets/4545925/17590384/3b45be2c-5ff7-11e6-9722-992f934f47f6.PNG)

**Comment by elibol** [comment]
Installation instructions have been updated. If you still haven't resolved your issue, please try the following.

Run `pip install ./ --no-cache --upgrade` from the root directory of the Azimuth repository. Make sure the `pip` and `python` binaries are pointing to those in your the anaconda installation:

```
PS > where.exe pip
C:\Users\{username}\AppData\Local\Continuum\Anaconda2\Scripts\pip.exe
```
