### ISSUE TITLE
explain why 30nt are needed

### ISSUE THREAD

**Issue by antonkulaga** [MicrosoftResearch/Azimuth#17]
As typical gRNA length is 20nt I wonder why 30nt are needed and how to define those nt (as I can have gRNA and 10 nt before or gRNA and 20nt after)

**Comment by jlistgarten** [comment]
See Supp. Figure 4 here:  http://biorxiv.org/content/early/2015/06/26/021568

**Comment by nextgenusfs** [comment]
For those of you who don't want to go look at the PDF..... its -4 on the 5' end and +3 after the PAM. So 20 bp gRNA, 3 bp PAM, and 7 bp flanking = 30 bp.

![image](https://user-images.githubusercontent.com/6164308/54783609-0ed2d880-4bdf-11e9-88b9-f6a3fc684507.png)
