### ISSUE TITLE
Negative guide scores

### ISSUE THREAD

**Issue by vineetgopal** [MicrosoftResearch/Azimuth#21]
Hello! We've noticed that occasionally, guides that we score will get a *negative* predicted score from azimuth. Here's an example:

```
> from azimuth.model_comparison import predict
> import numpy
> predict(numpy.array(['AACTGATTTCTGGCGTTTTCTTTCTGGCTC']), numpy.array([8905]), numpy.array([96]))
No model file specified, using V3_model_full
array([-0.04603427])
```

Empirically, it looks like negative scores are more likely to happen with peptide percentages closer to 100. However, from the Azimuth documentation (and the general understanding of CRISPR on-target scores, it looks like scores are expected to be between 0.0 and 1.0. Is this possibly a bug in the scoring system?

If it's helpful, this does not happen if the peptide percentage is set to 95 or less.

Thanks!

**Comment by jlistgarten** [comment]
Hi Vineet,

Although the training data were in the range 0.0 to 1.0, the final trained regression model we use can make predictions outside of this range. Still, we expect these to be somewhat rare. So no, there is no bug, and what you describe sounds reasonable. If it’s easier for your purposes, you could just set values to the closest part of the range 0.0-1.0 (i.e. negative values to 0, and values greater than 1.1 to 1.0).

Jennifer

**Comment by jjc2718** [comment]
The documentation has been updated to reflect Jennifer's response above.
