### ISSUE TITLE
Project website should link to data in the repo

### ISSUE THREAD

**Issue by hammer** [MicrosoftResearch/Azimuth#9]
The [project website](https://www.microsoft.com/en-us/research/project/azimuth/) sends me to http://www.jennifer.listgarten.com/azimuthFC_plus_RES_withPredictions.csv which says `Not Found [CFN #0005]`.

The data seems to be available in the repo though: https://github.com/MicrosoftResearch/Azimuth/blob/master/azimuth/FC_plus_RES_withPredictions.csv

**Comment by nfusi** [comment]
Thanks. We have updated the link on the website (the MSR webpages have been recently revamped and some links broke as a consequence).
